#  生成cinema java代码
cmd /c protoc.exe -IE:\workspace\tomgs-java\learning-proto\custom-protoc-plugin/src/main/proto/ --java_out=E:\workspace\tomgs-java\learning-proto\custom-protoc-plugin\target\generated-sources\protobuf/java cinema.proto

cmd /c protoc.exe -IE:\workspace\tomgs-java\learning-proto\custom-protoc-plugin/src/main/proto/ --java_out=E:\workspace\tomgs-java\learning-proto\custom-protoc-plugin\target\generated-sources\protobuf/java selfmd.proto